### ISSUE TITLE
DevPod commands on Linux are not being found

### ISSUE THREAD

**Issue by TiagoEzequiel** [3timeslazy/vscodium-devpodcontainers#14]
In this version `0.0.14` the extension commands are not being found, I reverted to version `0.0.13` and it is working perfectly. I am just reporting for the next version to be fixed =)

**Comment by herrwusel** [comment]
That was me at #10 then. It worked for me on Linux. I will test again.

**Comment by herrwusel** [comment]
I get this now :upside_down_face: 

![image](https://github.com/user-attachments/assets/e51886fe-21d8-4369-abf7-26edcd8b3f26)

**Comment by TiagoEzequiel** [comment]
@3timeslazy the base distribution is Archlinux and VSCodium is installed in `opt/vscodium-bin/`, the settings are in `$HOME/.config/VSCodium`, and the extensions in `$HOME/.vscode-oss/extension`.
After updating to version '0.0.14' it is no longer notifying when there is a `.devcontainer/devcontainer.json` json and when the `DevPod Containers : Open in Container` command is forced, the error that @herrwusel showed in the photo appears.

**Comment by 3timeslazy** [comment]
Update to 0.0.15. Should be fixed now

**Comment by 3timeslazy** [comment]
I'm a JS noob and ironically a commit [Remove things I dont understand](https://github.com/3timeslazy/vscodium-devpodcontainers/commit/f87ed3eb2e62f4f4b61b1e088931a41da6d39064) broke the vsix package bundling

**Comment by TiagoEzequiel** [comment]
Ok, it's fixed.
