### ISSUE TITLE
Add code formatter

### ISSUE THREAD

**Issue by 3timeslazy** [3timeslazy/vscodium-devpodcontainers#7]
Currently the code is messy, so it'd be nice to have a single code formatter. 

Requirements:
- Configured via file (don't think that's a problem)
- Keep the order of the arguments here: https://github.com/3timeslazy/vscodium-devpodcontainers/blob/9ff3832c0efae125c8a3e0f5cf578327edf21f67/src/devpod/commands.ts#L13-L19. I tried `prettier`, and it was nice overall, but I couldn't got it to not touch these lines. Hence the requirement.

**Comment by KhazAkar** [comment]
Quick proposition - prettier with simple configuration?

**Comment by 3timeslazy** [comment]
I think I should try one more time with prettier, you’re right

**Comment by KhazAkar** [comment]
I will look what is used around and propose something if I have it :)

**Comment by 3timeslazy** [comment]
Done here: https://github.com/3timeslazy/vscodium-devpodcontainers/commit/9d68d86c510fb0db053e3fcb765a8b1b97874f5f
